# Create New Entity Types in Entu
# This file contains HTTP requests to create the new entity types defined in F001-entu-entity-types.md

@host = entu.app
@account = esmuuseum
@token = {{esm_token}}
@esmuuseumEntityId = 66b6245c7efc9ac06a437ba0
@entityEntityId = 66b624597efc9ac06a437840
@propertyEntityId = 66b6245a7efc9ac06a437a42
@personEntityId = 66b6245a7efc9ac06a437920
@ylesandedFolderEntityId = 68691eb91749f351b9c82f68

###
# 0. Authenticate to get token
# @name auth
GET https://{{host}}/api/auth?account={{account}}
Authorization: Bearer {{esm_key}}


# A. Create entity types for the ESMuseum account

###
# 1. Create Kaart entity type
POST https://{{host}}/api/{{account}}/entity
Authorization: Bearer {{token}}
Content-Type: application/json

[
    {"_id": "686913e11749f351b9c82f1c"},
    {"type": "_type", "reference": "{{entityEntityId}}"},
    {"type": "name", "string": "kaart"},
    {"type": "label", "string": "Kaart", "language": "et"},
    {"type": "label", "string": "Map", "language": "en"},
    {"type": "label_plural", "string": "Kaardid", "language": "et"},
    {"type": "label_plural", "string": "Maps", "language": "en"},
    {"type": "_parent", "reference": "{{esmuuseumEntityId}}"}
]

###
@kaartEntityId = 686913e11749f351b9c82f1c

### add "add from" to Kaart entity type
POST https://{{host}}/api/{{account}}/entity/{{kaartEntityId}} HTTP/1.1
Accept-Encoding: deflate
Authorization: Bearer {{token}}
Content-Type: application/json; charset=utf-8

[
    {"type": "add_from", "reference": "{{esmuuseumEntityId}}"}
]

###
# 2. Create Asukoht entity type
POST https://{{host}}/api/{{account}}/entity
Authorization: Bearer {{token}}
Content-Type: application/json

[
    {"type": "_type", "reference": "{{entityEntityId}}"},
    {"type": "name", "string": "asukoht"},
    {"type": "label", "string": "Asukoht", "language": "et"},
    {"type": "label", "string": "Location", "language": "en"},
    {"type": "label_plural", "string": "Asukohad", "language": "et"},
    {"type": "label_plural", "string": "Locations", "language": "en"},
    {"type": "_parent", "reference": "{{esmuuseumEntityId}}"},
    {"type": "add_from", "reference": "{{kaartEntityId}}"}
]

###
@asukohtEntityId = 686914211749f351b9c82f28

###
# 3. Create Grupp entity type
POST https://{{host}}/api/{{account}}/entity
Authorization: Bearer {{token}}
Content-Type: application/json

[
    {"type": "_type", "reference": "{{entityEntityId}}"},
    {"type": "name", "string": "grupp"},
    {"type": "label", "string": "Grupp", "language": "et"},
    {"type": "label", "string": "Group", "language": "en"},
    {"type": "label_plural", "string": "Grupid", "language": "et"},
    {"type": "label_plural", "string": "Groups", "language": "en"},
    {"type": "_parent", "reference": "{{esmuuseumEntityId}}"}
]

###
@gruppEntityId = 686914521749f351b9c82f35

### add "add from" to Grupp entity type
POST https://{{host}}/api/{{account}}/entity/{{gruppEntityId}} HTTP/1.1
Accept-Encoding: deflate
Authorization: Bearer {{token}}
Content-Type: application/json; charset=utf-8

[
    {"type": "add_from", "reference": "{{esmuuseumEntityId}}"}
]

###
# 4. Create Ülesanne entity type
POST https://{{host}}/api/{{account}}/entity
Authorization: Bearer {{token}}
Content-Type: application/json

[
    {"type": "_type", "reference": "{{entityEntityId}}"},
    {"type": "name", "string": "ulesanne"},
    {"type": "label", "string": "Ülesanne", "language": "et"},
    {"type": "label", "string": "Task", "language": "en"},
    {"type": "label_plural", "string": "Ülesanded", "language": "et"},
    {"type": "label_plural", "string": "Tasks", "language": "en"},
    {"type": "_parent", "reference": "{{esmuuseumEntityId}}"}
]

###
@ulesanneEntityId = 686917231749f351b9c82f4c

### add "add from" to Ülesanne entity type
POST https://{{host}}/api/{{account}}/entity/{{ulesanneEntityId}} HTTP/1.1
Accept-Encoding: deflate
Authorization: Bearer {{token}}
Content-Type: application/json; charset=utf-8

[
    {"type": "add_from", "reference": "{{ylesandedFolderEntityId}}"}
]

###
# 5. Create Vastus entity type
POST https://{{host}}/api/{{account}}/entity
Authorization: Bearer {{token}}
Content-Type: application/json

[
  {"type": "_type", "reference": "{{entityEntityId}}"},
  {"type": "name", "string": "vastus"},
  {"type": "label", "string": "Vastus", "language": "et"},
  {"type": "label", "string": "Response", "language": "en"},
  {"type": "label_plural", "string": "Vastused", "language": "et"},
  {"type": "label_plural", "string": "Responses", "language": "en"},
  {"type": "_parent", "reference": "{{esmuuseumEntityId}}"},
  {"type": "add_from", "reference": "{{ulesanneEntityId}}", "entity_type": "ulesanne"}
]

###
@vastusEntityId = 686917401749f351b9c82f58


# B. Create property types

## 1. Kaart entity type properties

### 1.1. Create "name" property for Kaart entity type
POST https://{{host}}/api/{{account}}/entity
Authorization: Bearer {{token}}
Content-Type: application/json

[
    {"type": "_type", "reference": "{{propertyEntityId}}"},
    {"type": "_parent", "reference": "{{kaartEntityId}}"},
    {"type": "name", "string": "name"},
    {"type": "label", "string": "Nimi", "language": "et"},
    {"type": "label", "string": "Name", "language": "en"},
    {"type": "type", "string": "string"},
    {"type": "datatype", "string": "string"},
    {"type": "public", "boolean": true},
    {"type": "search", "boolean": true},
    {"type": "ordinal", "number": 1}
]

### 1.2. Create "kirjeldus" property for Kaart entity type
POST https://{{host}}/api/{{account}}/entity
Authorization: Bearer {{token}}
Content-Type: application/json

[
    {"type": "_type", "reference": "{{propertyEntityId}}"},
    {"type": "_parent", "reference": "{{kaartEntityId}}"},
    {"type": "name", "string": "kirjeldus"},
    {"type": "label", "string": "Kirjeldus", "language": "et"},
    {"type": "label", "string": "Description", "language": "en"},
    {"type": "type", "string": "string"},
    {"type": "datatype", "string": "text"},
    {"type": "public", "boolean": true},
    {"type": "search", "boolean": true},
    {"type": "ordinal", "number": 2}
]

### 1.3. Create "url" property for Kaart entity type
POST https://{{host}}/api/{{account}}/entity
Authorization: Bearer {{token}}
Content-Type: application/json

[
    {"type": "_type", "reference": "{{propertyEntityId}}"},
    {"type": "_parent", "reference": "{{kaartEntityId}}"},
    {"type": "name", "string": "url"},
    {"type": "label", "string": "URL", "language": "et"},
    {"type": "label", "string": "URL", "language": "en"},
    {"type": "type", "string": "string"},
    {"type": "datatype", "string": "url"},
    {"type": "public", "boolean": true},
    {"type": "multilingual", "boolean": false},
    {"type": "ordinal", "number": 3}
]

## 2. Asukoht entity type properties

### 2.1. Create "name" property for Asukoht entity type
POST https://{{host}}/api/{{account}}/entity
Authorization: Bearer {{token}}
Content-Type: application/json

[
    {"type": "_type", "reference": "{{propertyEntityId}}"},
    {"type": "_parent", "reference": "{{asukohtEntityId}}"},
    {"type": "name", "string": "name"},
    {"type": "label", "string": "Nimi", "language": "et"},
    {"type": "label", "string": "Name", "language": "en"},
    {"type": "type", "string": "string"},
    {"type": "datatype", "string": "string"},
    {"type": "public", "boolean": true},
    {"type": "search", "boolean": true},
    {"type": "ordinal", "number": 1}
]

### 2.2. Create "kirjeldus" property for Asukoht entity type
POST https://{{host}}/api/{{account}}/entity
Authorization: Bearer {{token}}
Content-Type: application/json

[
    {"type": "_type", "reference": "{{propertyEntityId}}"},
    {"type": "_parent", "reference": "{{asukohtEntityId}}"},
    {"type": "name", "string": "kirjeldus"},
    {"type": "label", "string": "Kirjeldus", "language": "et"},
    {"type": "label", "string": "Description", "language": "en"},
    {"type": "type", "string": "string"},
    {"type": "datatype", "string": "text"},
    {"type": "public", "boolean": true},
    {"type": "search", "boolean": true},
    {"type": "ordinal", "number": 2}
]

### 2.3. Create "long" property for Asukoht entity type
POST https://{{host}}/api/{{account}}/entity
Authorization: Bearer {{token}}
Content-Type: application/json

[
    {"type": "_type", "reference": "{{propertyEntityId}}"},
    {"type": "_parent", "reference": "{{asukohtEntityId}}"},
    {"type": "name", "string": "long"},
    {"type": "label", "string": "Pikkuskraad", "language": "et"},
    {"type": "label", "string": "Longitude", "language": "en"},
    {"type": "type", "string": "number"},
    {"type": "datatype", "string": "decimal"},
    {"type": "public", "boolean": true},
    {"type": "ordinal", "number": 3}
]

### 2.4. Create "lat" property for Asukoht entity type
POST https://{{host}}/api/{{account}}/entity
Authorization: Bearer {{token}}
Content-Type: application/json

[
    {"type": "_type", "reference": "{{propertyEntityId}}"},
    {"type": "_parent", "reference": "{{asukohtEntityId}}"},
    {"type": "name", "string": "lat"},
    {"type": "label", "string": "Laiuskraad", "language": "et"},
    {"type": "label", "string": "Latitude", "language": "en"},
    {"type": "type", "string": "number"},
    {"type": "datatype", "string": "decimal"},
    {"type": "public", "boolean": true},
    {"type": "ordinal", "number": 4}
]

### 2.5. Create "photo" property for Asukoht entity type
POST https://{{host}}/api/{{account}}/entity
Authorization: Bearer {{token}}
Content-Type: application/json

[
    {"type": "_type", "reference": "{{propertyEntityId}}"},
    {"type": "_parent", "reference": "{{asukohtEntityId}}"},
    {"type": "name", "string": "photo"},
    {"type": "label", "string": "Pilt", "language": "et"},
    {"type": "label", "string": "Picture", "language": "en"},
    {"type": "type", "string": "file"},
    {"type": "datatype", "string": "image"},
    {"type": "public", "boolean": true},
    {"type": "ordinal", "number": 5}
]

### 2.6. Create "link" property for Asukoht entity type
POST https://{{host}}/api/{{account}}/entity
Authorization: Bearer {{token}}
Content-Type: application/json

[
    {"type": "_type", "reference": "{{propertyEntityId}}"},
    {"type": "_parent", "reference": "{{asukohtEntityId}}"},
    {"type": "name", "string": "link"},
    {"type": "label", "string": "Link", "language": "et"},
    {"type": "label", "string": "Link", "language": "en"},
    {"type": "type", "string": "string"},
    {"type": "datatype", "string": "url"},
    {"type": "public", "boolean": true},
    {"type": "multilingual", "boolean": false},
    {"type": "ordinal", "number": 6}
]

## 3. Grupp entity type properties

### 3.1. Create "nimi" property for Grupp entity type
POST https://{{host}}/api/{{account}}/entity
Authorization: Bearer {{token}}
Content-Type: application/json

[
    {"type": "_type", "reference": "{{propertyEntityId}}"},
    {"type": "_parent", "reference": "{{gruppEntityId}}"},
    {"type": "name", "string": "name"},
    {"type": "label", "string": "Nimi", "language": "et"},
    {"type": "label", "string": "Name", "language": "en"},
    {"type": "type", "string": "string"},
    {"type": "datatype", "string": "string"},
    {"type": "public", "boolean": true},
    {"type": "search", "boolean": true},
    {"type": "ordinal", "number": 1}
]

### 3.2. Create "kirjeldus" property for Grupp entity type
POST https://{{host}}/api/{{account}}/entity
Authorization: Bearer {{token}}
Content-Type: application/json

[
    {"type": "_type", "reference": "{{propertyEntityId}}"},
    {"type": "_parent", "reference": "{{gruppEntityId}}"},
    {"type": "name", "string": "kirjeldus"},
    {"type": "label", "string": "Kirjeldus", "language": "et"},
    {"type": "label", "string": "Description", "language": "en"},
    {"type": "type", "string": "string"},
    {"type": "datatype", "string": "text"},
    {"type": "public", "boolean": true},
    {"type": "multilingual", "boolean": true},
    {"type": "search", "boolean": true},
    {"type": "ordinal", "number": 2}
]

### 3.3. Create "grupijuht" property for Grupp entity type
POST https://{{host}}/api/{{account}}/entity
Authorization: Bearer {{token}}
Content-Type: application/json

[
    {"type": "_type", "reference": "{{propertyEntityId}}"},
    {"type": "_parent", "reference": "{{gruppEntityId}}"},
    {"type": "name", "string": "grupijuht"},
    {"type": "label", "string": "Grupijuht", "language": "et"},
    {"type": "label", "string": "Group Leader", "language": "en"},
    {"type": "type", "string": "reference"},
    {"type": "reference_to", "reference": "{{personEntityId}}"},
    {"type": "public", "boolean": true},
    {"type": "ordinal", "number": 3}
]

## 4. Ülesanne entity type properties

### 4.1. Create "nimi" property for Ülesanne entity type
POST https://{{host}}/api/{{account}}/entity
Authorization: Bearer {{token}}
Content-Type: application/json

[
    {"type": "_type", "reference": "{{propertyEntityId}}"},
    {"type": "_parent", "reference": "{{ulesanneEntityId}}"},
    {"type": "name", "string": "name"},
    {"type": "label", "string": "Nimi", "language": "et"},
    {"type": "label", "string": "Name", "language": "en"},
    {"type": "type", "string": "string"},
    {"type": "datatype", "string": "string"},
    {"type": "public", "boolean": true},
    {"type": "search", "boolean": true},
    {"type": "ordinal", "number": 1}
]

### 4.2. Create "kirjeldus" property for Ülesanne entity type
POST https://{{host}}/api/{{account}}/entity
Authorization: Bearer {{token}}
Content-Type: application/json

[
    {"type": "_type", "reference": "{{propertyEntityId}}"},
    {"type": "_parent", "reference": "{{ulesanneEntityId}}"},
    {"type": "name", "string": "kirjeldus"},
    {"type": "label", "string": "Kirjeldus", "language": "et"},
    {"type": "label", "string": "Description", "language": "en"},
    {"type": "type", "string": "string"},
    {"type": "datatype", "string": "text"},
    {"type": "public", "boolean": true},
    {"type": "search", "boolean": true},
    {"type": "ordinal", "number": 2}
]

### 4.3. Create "tähtaeg" property for Ülesanne entity type
POST https://{{host}}/api/{{account}}/entity
Authorization: Bearer {{token}}
Content-Type: application/json

[
    {"type": "_type", "reference": "{{propertyEntityId}}"},
    {"type": "_parent", "reference": "{{ulesanneEntityId}}"},
    {"type": "name", "string": "tahtaeg"},
    {"type": "label", "string": "Tähtaeg", "language": "et"},
    {"type": "label", "string": "Deadline", "language": "en"},
    {"type": "type", "string": "datetime"},
    {"type": "public", "boolean": true},
    {"type": "ordinal", "number": 3}
]

### 4.4. Create "kaart" property for Ülesanne entity type
POST https://{{host}}/api/{{account}}/entity
Authorization: Bearer {{token}}
Content-Type: application/json

[
    {"type": "_type", "reference": "{{propertyEntityId}}"},
    {"type": "_parent", "reference": "{{ulesanneEntityId}}"},
    {"type": "name", "string": "kaart"},
    {"type": "label", "string": "Kaart", "language": "et"},
    {"type": "label", "string": "Map", "language": "en"},
    {"type": "type", "string": "reference"},
    {"type": "reference_to", "reference": "{{kaartEntityId}}"},
    {"type": "public", "boolean": true},
    {"type": "ordinal", "number": 4}
]

### 4.5. Create "grupp" property for Ülesanne entity type
POST https://{{host}}/api/{{account}}/entity
Authorization: Bearer {{token}}
Content-Type: application/json

[
    {"type": "_type", "reference": "{{propertyEntityId}}"},
    {"type": "_parent", "reference": "{{ulesanneEntityId}}"},
    {"type": "name", "string": "grupp"},
    {"type": "label", "string": "Grupp", "language": "et"},
    {"type": "label", "string": "Group", "language": "en"},
    {"type": "type", "string": "reference"},
    {"type": "reference_to", "reference": "{{gruppEntityId}}"},
    {"type": "public", "boolean": true},
    {"type": "ordinal", "number": 5}
]

## 5. Vastus entity type properties

### 5.1. Create "asukoht" property for Vastus entity type
POST https://{{host}}/api/{{account}}/entity
Authorization: Bearer {{token}}
Content-Type: application/json

[
    {"type": "_type", "reference": "{{propertyEntityId}}"},
    {"type": "_parent", "reference": "{{vastusEntityId}}"},
    {"type": "name", "string": "asukoht"},
    {"type": "label", "string": "Asukoht", "language": "et"},
    {"type": "label", "string": "Location", "language": "en"},
    {"type": "type", "string": "reference"},
    {"type": "reference_to", "reference": "{{asukohtEntityId}}"},
    {"type": "public", "boolean": true},
    {"type": "ordinal", "number": 1}
]

### 5.2. Create "kirjeldus" property for Vastus entity type
POST https://{{host}}/api/{{account}}/entity
Authorization: Bearer {{token}}
Content-Type: application/json

[
    {"type": "_type", "reference": "{{propertyEntityId}}"},
    {"type": "_parent", "reference": "{{vastusEntityId}}"},
    {"type": "name", "string": "kirjeldus"},
    {"type": "label", "string": "Kirjeldus", "language": "et"},
    {"type": "label", "string": "Description", "language": "en"},
    {"type": "type", "string": "string"},
    {"type": "datatype", "string": "text"},
    {"type": "public", "boolean": true},
    {"type": "search", "boolean": true},
    {"type": "ordinal", "number": 2}
]

### 5.3. Create "photo" property for Vastus entity type
POST https://{{host}}/api/{{account}}/entity
Authorization: Bearer {{token}}
Content-Type: application/json

[
    {"type": "_type", "reference": "{{propertyEntityId}}"},
    {"type": "_parent", "reference": "{{vastusEntityId}}"},
    {"type": "name", "string": "photo"},
    {"type": "label", "string": "Pilt", "language": "et"},
    {"type": "label", "string": "Picture", "language": "en"},
    {"type": "type", "string": "file"},
    {"type": "datatype", "string": "image"},
    {"type": "public", "boolean": true},
    {"type": "ordinal", "number": 3}
]

