# Entu API HTTP Request Examples
#
# Use with VS Code REST Client extension or similar tools.
# Replace {{esm_key}} and {{esm_token}} with your own credentials or use environment variables.

@hostname=entu.app/api
@account=esmuuseum

### Auth
GET {{hostname}}/auth?account={{account}} HTTP/1.1
Accept-Encoding: deflate
Authorization: Bearer {{esm_key}}

### Account
GET {{hostname}}/{{account}} HTTP/1.1
Accept-Encoding: deflate
Authorization: Bearer {{esm_token}}

### Entity entities GET
GET {{hostname}}/{{account}}/entity?_type.string=entity&props=name.string HTTP/1.1
Accept-Encoding: deflate
Authorization: Bearer {{esm_token}}

### List all entity types
GET {{hostname}}/{{account}}/entity?_type.string=entity HTTP/1.1
Accept-Encoding: deflate
Authorization: Bearer {{esm_token}}

### Entity GET
GET {{hostname}}/{{account}}/entity/66d6ead6f2daf46b3143eefb HTTP/1.1
Accept-Encoding: deflate
Authorization: Bearer {{esm_token}}

### Entity GET folder
GET {{hostname}}/{{account}}/entity?_type.string=folder HTTP/1.1
Accept-Encoding: deflate
Authorization: Bearer {{esm_token}}

### Aggregate entity
GET {{hostname}}/{{account}}/entity/66d87895f2daf46b3144cc4c/aggregate HTTP/1.1
Accept-Encoding: deflate
Authorization: Bearer {{esm_token}}

### POST inheritrights
POST {{hostname}}/{{account}}/entity/66d87895f2daf46b3144cc4c HTTP/1.1
Accept-Encoding: deflate
Authorization: Bearer {{esm_token}}
Content-Type: application/json; charset=utf-8

[
    {"type": "_inheritrights", "boolean": true}
]

### DELETE entity
DELETE {{hostname}}/{{account}}/entity/6868f53c1749f351b9c82e98
Accept-Encoding: deflate
Authorization: Bearer {{esm_token}}
Content-Type: application/json; charset=utf-8

### Entity GET kaart id's
GET {{hostname}}/{{account}}/entity?_type.string=kaart&props=_id&limit=10000 HTTP/1.1
Accept-Encoding: deflate
Authorization: Bearer {{esm_token}}

### DELETE entities
@type_to_delete=kaart
###
DELETE {{hostname}}/{{account}}/entity?_type.string={{type_to_delete}}
Accept-Encoding: deflate
Authorization: Bearer {{esm_token}}
Content-Type: application/json; charset=utf-8

### File upload (get upload url)
POST {{hostname}}/{{account}}/entity/66eabbe42e92de098dfc8125 HTTP/1.1
Accept-Encoding: deflate
Authorization: Bearer {{esm_token}}
Content-Type: application/json; charset=utf-8

[
    {
        "type": "photo", 
        "filename": "0003, aalberg, viktor.png", 
        "filesize": 231269, 
        "filetype": "image/png"
    }
]
