#!/bin/bash
# migrate-features.sh - Migrate historical F001-F026 to spec-kit specs/ structure

set -e

echo "Starting feature migration from .specify/features/ to specs/"

# Change to features directory
cd .specify/features

# Counter for tracking progress
count=0

# Migrate each F0*.md file
for file in F0*.md; do
    # Skip if not a file
    [ -f "$file" ] || continue
    
    # Extract number (F001 → 001, F010 → 010, F023.1 → 023.1)
    num=$(echo "$file" | sed 's/^F0*//' | sed 's/-.*//')
    # Only use printf for whole numbers, keep decimals as-is
    if [[ "$num" =~ \. ]]; then
        # Has decimal, keep as-is but ensure proper format
        num=$(echo "$num" | sed 's/^0*//')
        num=$(printf "%03s" "$num")
    else
        # Whole number, format as 3 digits
        num=$(printf "%03d" $((10#$num)))
    fi
    
    # Extract name (F001-feature-name.md → feature-name)
    name=$(echo "$file" | sed 's/F[0-9]*-//' | sed 's/\.md$//')
    
    # Create spec directory
    mkdir -p "../../specs/$num-$name"
    
    # Copy file to spec.md (keep original for now)
    cp "$file" "../../specs/$num-$name/spec.md"
    
    count=$((count + 1))
    echo "[$count] Migrated: $file → specs/$num-$name/spec.md"
done

# Return to repo root
cd ../..

# Create specs README.md
cat > specs/README.md << 'EOF'
# Feature Specifications

This directory contains all feature specifications following spec-kit conventions.

## Structure

Each feature has its own directory:

```text
specs/
├── 001-feature-name/
│   ├── spec.md      # Feature specification
│   ├── plan.md      # Implementation plan (generated by /plan)
│   └── tasks.md     # Task breakdown (generated by /tasks)
├── 002-another-feature/
│   └── spec.md
└── README.md        # This file
```

## Historical Features

Features **001-026** were migrated from legacy `.copilot-workspace/features/` (F001-F026).

These are historical feature specifications from before spec-kit integration.

## New Features

Features **027+** are created using the spec-kit workflow:

```bash
/specify "Add new feature description"
```

This command will:
1. Find the highest feature number (e.g., 026)
2. Create next number directory (e.g., `specs/027-feature-name/`)
3. Generate `spec.md` from template
4. Create feature branch `027-feature-name`

## Workflow

After creating a spec with `/specify`:

1. **Plan**: `/plan` generates `plan.md` in the feature directory
2. **Tasks**: `/tasks` generates `tasks.md` with implementation breakdown
3. **Implement**: `/implement` executes tasks and creates the feature

See `.specify/README.md` for complete workflow documentation.

---

**Note**: Original feature files remain in `.specify/features/` for reference until migration is confirmed successful.
EOF

echo ""
echo "✅ Migration complete!"
echo "   Migrated $count features to specs/"
echo "   Created specs/README.md"
echo ""
echo "Next steps:"
echo "1. Review specs/ directory structure"
echo "2. Test create-new-feature.sh (should create 027-*)"
echo "3. If successful, archive .specify/features/ to .specify/archive/"
